### ISSUE TITLE
好きなときにアラートを出したい！

### ISSUE THREAD

**Issue by Haruka0522** [YuseiIto/tokyo-alert#1]
現状ではページを開いたら勝手に定期的にアラートが出されている

好きなときに好きなだけ東京アラートが出せるように”東京アラート”ボタンを作りたい！

**Comment by Haruka0522** [comment]
そのうちやります

**Comment by YuseiIto** [comment]
気づいてなかったです。ちゃんとissueまで立ててるの草しか生えません。
